[package]
name = "pgstatprof"
version = "0.0.1"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]

[dependencies]
postgres = "0.15"
getopts = "0.2"
users = "0.7"
time = "0.1"
regex = "1"
lazy_static = "1.0"
