[package]
name = "pgstatprof"
version = "0.1.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]
edition = "2018"

[dependencies]
postgres = "0.17"
getopts = "0.2"
users = "0.9"
time = "0.2"
regex = "1"
lazy_static = "1.0"
